version: '3.8'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - "3306:3306"
        restart: always

    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - db
        restart: always

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_HOST: ${DATABASE_HOST}
        ports:
            - "3000:3000"
        depends_on:
            - db
        restart: always

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin
        ports:
            - "8011:80"
        restart: always
        environment:
            PMA_HOST: ${DATABASE_HOST}
            PMA_USER: ${DATABASE_USER}
            PMA_PASSWORD: ${DATABASE_PASSWORD}

volumes:
    db-data:
